services:
  db:
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
